#!/usr/bin/env bash

#docker run --name btcpool.zookeeper --restart always -d zookeeper

docker run --name btcpool.kafka -p 2181:2181 -p 9092:9092 --env ADVERTISED_HOST=`docker-machine ip \`docker-machine active\`` --env ADVERTISED_PORT=9092 spotify/kafka

docker run --name btcpool --detach -t --volume ~/projects/forks/btcpool:/btcpool ubuntu
